/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LiquidatorHelperInterface extends ethers.utils.Interface {
  functions: {
    "ADDRESSES_PROVIDER()": FunctionFragment;
    "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)": FunctionFragment;
    "LENDING_POOL()": FunctionFragment;
    "executeOperation(address[],uint256[],uint256[],address,bytes)": FunctionFragment;
    "fund(address,uint256)": FunctionFragment;
    "fundAndLiquidate(address,address,address,address,uint256,bool)": FunctionFragment;
    "fundLiquidateAndSell(address,address,address,address,uint256,bool)": FunctionFragment;
    "liquidationCall(address,address,address,address,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FlashLoanLiquidateAndSell",
    values: [string, string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "LENDING_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [string[], BigNumberish[], BigNumberish[], string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fund",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundAndLiquidate",
    values: [string, string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLiquidateAndSell",
    values: [string, string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationCall",
    values: [string, string, string, string, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FlashLoanLiquidateAndSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LENDING_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundAndLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundLiquidateAndSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationCall",
    data: BytesLike
  ): Result;

  events: {};
}

export class LiquidatorHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LiquidatorHelperInterface;

  functions: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ADDRESSES_PROVIDER()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    FlashLoanLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    LENDING_POOL(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "LENDING_POOL()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeOperation(address[],uint256[],uint256[],address,bytes)"(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fund(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "fund(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fundAndLiquidate(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "fundAndLiquidate(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fundLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "fundLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    liquidationCall(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "liquidationCall(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

  "ADDRESSES_PROVIDER()"(overrides?: CallOverrides): Promise<string>;

  FlashLoanLiquidateAndSell(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)"(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  LENDING_POOL(overrides?: CallOverrides): Promise<string>;

  "LENDING_POOL()"(overrides?: CallOverrides): Promise<string>;

  executeOperation(
    assets: string[],
    amounts: BigNumberish[],
    premiums: BigNumberish[],
    initiator: string,
    params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeOperation(address[],uint256[],uint256[],address,bytes)"(
    assets: string[],
    amounts: BigNumberish[],
    premiums: BigNumberish[],
    initiator: string,
    params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fund(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "fund(address,uint256)"(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fundAndLiquidate(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "fundAndLiquidate(address,address,address,address,uint256,bool)"(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fundLiquidateAndSell(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "fundLiquidateAndSell(address,address,address,address,uint256,bool)"(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    borrower: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  liquidationCall(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    user: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "liquidationCall(address,address,address,address,uint256,bool)"(
    pool: string,
    collateralAsset: string,
    debtAsset: string,
    user: string,
    debtToCover: BigNumberish,
    receiveAToken: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

    "ADDRESSES_PROVIDER()"(overrides?: CallOverrides): Promise<string>;

    FlashLoanLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    LENDING_POOL(overrides?: CallOverrides): Promise<string>;

    "LENDING_POOL()"(overrides?: CallOverrides): Promise<string>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "executeOperation(address[],uint256[],uint256[],address,bytes)"(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    fund(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "fund(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fundAndLiquidate(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "fundAndLiquidate(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    fundLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "fundLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidationCall(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "liquidationCall(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<BigNumber>;

    "ADDRESSES_PROVIDER()"(overrides?: CallOverrides): Promise<BigNumber>;

    FlashLoanLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    LENDING_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    "LENDING_POOL()"(overrides?: CallOverrides): Promise<BigNumber>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeOperation(address[],uint256[],uint256[],address,bytes)"(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    fund(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "fund(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    fundAndLiquidate(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "fundAndLiquidate(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    fundLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "fundLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    liquidationCall(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "liquidationCall(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADDRESSES_PROVIDER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ADDRESSES_PROVIDER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FlashLoanLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "FlashLoanLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    LENDING_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "LENDING_POOL()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeOperation(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeOperation(address[],uint256[],uint256[],address,bytes)"(
      assets: string[],
      amounts: BigNumberish[],
      premiums: BigNumberish[],
      initiator: string,
      params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fund(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "fund(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fundAndLiquidate(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "fundAndLiquidate(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fundLiquidateAndSell(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "fundLiquidateAndSell(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      borrower: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    liquidationCall(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "liquidationCall(address,address,address,address,uint256,bool)"(
      pool: string,
      collateralAsset: string,
      debtAsset: string,
      user: string,
      debtToCover: BigNumberish,
      receiveAToken: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
